using System;
using System.Globalization;
using System.IO;
using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Acc.Api.Interface;
using Acc.Api.Models;
using Acc.Api.Services;
using Swashbuckle.AspNetCore.Swagger;
using SwaggerOptions = Acc.Api.Documentasion.SwaggerOptions;

namespace Acc.Api
{
    public class Startup
    {
        public Startup(IConfiguration configuration, IHostingEnvironment env)
        {
            Configuration = configuration;
            Env = env;
        }

        public IConfiguration Configuration { get; }
        public IHostingEnvironment Env { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(option =>
            {
                option.AddPolicy("AnyOrigin", builder =>
                {
                    builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
                    .AllowCredentials();

                });

            });


            //services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.
                //AddMvc().
                AddMvc(options =>
                {
                    options.RespectBrowserAcceptHeader = true; // false by default
                    //options.InputFormatters.Insert(0, new RawRequestBodyFormatter());
                }).
                SetCompatibilityVersion(CompatibilityVersion.Version_2_2).//;
                AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver()).
                AddJsonOptions(options => options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Local);

            AppSettings settings = Configuration.GetSection("appSetting").Get<AppSettings>();
            services.AddSingleton(settings);
            //services.AddTransient<IDynamicService, DynamicService>();
            services.AddTransient<IAuthService, AuthServices>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IHostingEnvironment>(Env);
            services.AddHttpContextAccessor();

            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Info { Title = "Starter Core", Version = "v1" });
                options.OperationFilter<MyHeaderFilter>();
                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //... and tell Swagger to use those XML comments.
                options.IncludeXmlComments(xmlPath);
                //options.AddSecurityDefinition("Custom", new BasicAuthScheme { Description = "Custom Auth" });
                //options.OperationFilter<SwaggerFileOperationFilter>();
                
                //options.OperationFilter<AddAuthorizationHeader>();
                //options.AddSecurityDefinition("Custom", new ApiKeyScheme
                //{
                //    Description = "Standard Authorization header using the Bearer scheme. Example: \"{token}\"",
                //    In = "header",
                //    Name = "Token",
                //    Type = "apiKey"
                //});
            });
            //services.AddSwaggerGen(c =>
            //{
            //    c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            //});



        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors(builder => builder.AllowAnyHeader()
            .AllowAnyOrigin()
            .WithMethods("GET", "POST", "PUT", "DELETE", "OPTIONS"));

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseSwagger();
            var swaggerOptions = new SwaggerOptions();
            Configuration.GetSection(nameof(SwaggerOptions)).Bind(swaggerOptions);

            //app.UseSwagger(option =>
            //{
            //    option.RouteTemplate = swaggerOptions.JsonRoute;
            //});
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
            });

            //app.UseSwaggerUI(option =>
            //{
            //    option.SwaggerEndpoint(swaggerOptions.UiEndpoint, swaggerOptions.Description);
            //});

            // set culture agar format datetime dd/MM/yyyy
            var supportedCultures = new[]
                {
                   new CultureInfo("en-GB"),

                };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("en-GB"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            //app.UseCookiePolicy();

            app.UseMvc(routes =>
            {
                //routes.MapRoute(
                //    name: "default",
                //    template: "{controller=Home}/{action=Index}/{id?}");
                routes.MapRoute(
                    name: "default",
                    template: "ACC.API/{controller}/{action}/{id?}");
            });
        }
    }
}
